bentyne/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
# Uncomment the next two lines to enable the admin:
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from skylark.models import Settings
from skylark.models import SettingsBlog as blog_conf
from skylark.models import ContactSettings as contact_conf

from skylark.views import success_contact, contact_send

try:
    blog_settings = blog_conf.objects.get(id=1)
    blog_url = blog_settings.blog_url
    contact_settings = contact_conf.objects.get(id=1)
    contact_url = contact_settings.url
    contact_succes = contact_settings.succes_url
except ObjectDoesNotExist:
    blog_url = 'blog/'
    contact_url = 'contact/'
    contact_succes = 'contact/succes/'


urlpatterns = patterns('',
        # Examples:
        # url(r'^$', 'bentyne.views.home', name='home'),
        # url(r'^bentyne/', include('bentyne.foo.urls')),

        # Uncomment the admin/doc line below to enable admin documentation:
        # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

        url(r'^comments/', include('django.contrib.comments.urls')),
        url(r'^content/(?P<title>\w+)', 'cheryl.views.see_content',
            name="see_content"),
        )

urlpatterns += patterns('',
        url(r'^skylark/', include('skylark.urls')),
        (r'^auth/', include('userena.urls')),
        (r'^search/', include('haystack.urls')),
        )

urlpatterns += patterns('',
        url(r'^%s' % contact_url, contact_send),
        url(r'^%s' % contact_succes, success_contact),
        url(r'^%s' % blog_url, include('brasil.urls') ),
        url(r'^(?P<page_url>[\w\d_/-]+)/$', 'cheryl.views.page', name='page_view'),
        url(r'^$', 'cheryl.views.index', name='index_page')
        )


urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
        )

#BlogURLChangued

#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued

#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued

#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued

#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued
#BlogURLChangued

brasil/urls.py
from django.conf.urls.defaults import patterns, include, url
# Blog - features
from brasil.views import blog_index, blog_detail
from brasil.feeds import PostsFeed

urlpatterns = patterns('',
        url(r'^$', blog_index, name="brasil_index"),
        url(r'^feed/$', PostsFeed()),
        url(r'^(?P<slug>[-\w]+)/$', blog_detail, name="brasil_detail"),
        )

oriel/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from oriel.views import PictureCreateView, PictureDeleteView
from oriel.views import gallery_list, add_gallery, edit_gallery, view_gallery
from oriel.views import show_gallery
from oriel.views import edit_picture, delete_picture

urlpatterns = patterns('',
    # (r'^new/$', PictureCreateView.as_view(), {}, 'upload-new'),
    url(r'^upload/(?P<slug>[-\w]+)/$', PictureCreateView.as_view(), {}, 'upload-new'),
    url(r'^add/$', add_gallery, name='gallery-new'),
    url(r'^show/(?P<slug>[-\w]+)/$', show_gallery, name='gallery-show'),
    url(r'^$', gallery_list, name='oriel_index'),
    url(r'^(?P<slug>[-\w]+)/$',  view_gallery, name='gallery-edit'),
    (r'^rm/picture/(?P<pk>\d+)/$', login_required(PictureDeleteView.as_view()),
        {}, 'upload-delete'),
    url(r'^picture/(?P<id>\d+)/$', edit_picture, {}, 'picture-edit'),
    url(r'^delete/picture/(?P<id>\d+)/$', delete_picture, {}, 'picture-delete'),
)

skylark/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from skylark.views import add_post, delete_post, edit_post
from skylark.views import dashboard
from skylark.views import settings, settings_blog, contact_settings
from skylark.views import post_list
from skylark.views import tags_post, tag_post
from cheryl.views import index_pages, index_content
from brasil.views import blog_toggle
from cheryl.views import add_page, modify_page, delete_page
from cheryl.views import (add_content, modify_content,
        delete_content, save_inlinedit)

urlpatterns = patterns('',
        url(r'^$', dashboard, name='skylark_index'),
        url(r'^dashboard/$', dashboard, name='skylark_dashboard'),
        url(r'^brasil/add/$', add_post, name='blog_add_post'),
        url(r'^brasil/delete/(\d+)/$', delete_post,
            name='blog_delete_post'),
        url(r'^brasil/list/$', post_list,
            name='blog_add_post'),
        url(r'^brasil/(\d+)/$', edit_post, name='blog_edit'),
        url(r'^brasil/$', add_post, name='brasil_blog_index'),
        url(r'^brasil/tags/$', tags_post, name='tags'),
        url(r'^brasil/tags/(?P<name>[-\w]+)/$', tag_post, name='tag'),
        url(r'^brasil/toggle/(?P<id>\d+)/$', blog_toggle, name="brasil_toggle"),
        # url(r'^cheryl/?P<id>(\d+)/delete/$', delete_post,
        #     name='blog_delete_post'),
        # url(r'^cheryl/?P<id>(\d+)/edit/$', delete_post,
        #     name='blog_edit_post'),
        # # Brasil pages admin urls
        # url(r'^cheryl/$', brasil_index, name='brasil_index'),
        # url(r'^cheryl/edit/$', brasil_edit, name='brasil_edit'),
        url(r'^cheryl/$', index_pages  ,name='cheryl_list'),
        url(r'^cheryl/add/$', add_page, name='cheryl_add_page'),
        url(r'^cheryl/edit/(?P<id>\d+)/$', modify_page , name='cheryl_edit'),
        url(r'^cheryl/delete/(?P<id>\d+)/$', delete_page , name='cheryl_delete'),
        url(r'^cheryl/content/$', index_content  ,name='cheryl_list'),
        url(r'^cheryl/content/add/$', add_content  ,name='cheryl_list'),
        url(r'^cheryl/content/save/$', save_inlinedit, name='inlineedit'),
        url(r'^cheryl/content/delete/(?P<id>\d+)/$', delete_content  ,name='cheryl_list'),
        url(r'^cheryl/content/(?P<id>\d+)/$', modify_content  ,name='cheryl_list'),
        url(r'^oriel/', include('oriel.urls'), ),
        url(r'^settings/$', direct_to_template, {'template':'preferences.html'}, name="index_settings"),
        url(r'^help/$', direct_to_template, {'template':'help.html'}, name="help"),
        url(r'^settings/page/$', settings, name="settings"),
        url(r'^settings/blog/$', settings_blog, name="settings_blog"),
        url(r'^settings/contact/$', contact_settings, name="settings_contact"),
        # (r'^skylark/users/', include('registration.backends.default.urls') ),
        # url(r'^cheryl/?P<id>(\d+)/delete/$', delete_post,
        #     name='brasil_delete_page'),
        # url(r'^cheryl/?P<id>(\d+)/edit/$', delete_post,
        #     name='brasil_edit_page'),
        )

brasil/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager
from django.contrib.comments.moderation import CommentModerator, moderator
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    creation_date = models.DateTimeField(auto_now_add=True, auto_now=True,
            blank=False, null=False)
    slug = models.SlugField(editable=False)
    enable_comments = models.BooleanField()
    published = models.BooleanField(default=False)
    body = models.TextField()
    autor = models.ForeignKey(User, blank=True, null=True, editable=False)
    tags = TaggableManager()

    def __unicode__(self):
        return u'%s' % self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('brasil.views.blog_detail', [str(self.slug)])

class PostCommentModerator(CommentModerator):
    email_notification = True
    enable_field = 'enable_comments'

moderator.register(Post, PostCommentModerator)

skylark/models.py
from django.conf import settings
from django.db import models
from django.contrib.sites.models import Site
from django.core.exceptions import ObjectDoesNotExist
import os
# Create your models here.

try:
    site = Site.objects.get(id=1)
except:
    class Site:
        name = 'bad_example'
        domain = 'bad_example.com'
    site = Site()

def get_themes():
    for t in os.listdir(os.path.join(settings.PROJECT_ROOT, 'themes')):
        if os.path.basename(t) != 'static':
            if os.path.basename(t) != '__init__.py':
                if os.path.basename(t) != '__init__.pyc':
                    yield t

THEMES = tuple( (t, t) for t in get_themes())

class Settings(models.Model):
    site_name = models.CharField(max_length=500,
            default=site.name)
    site_domain = models.URLField(default=site.domain)
    site_theme = models.CharField(max_length=100, choices=THEMES)
    def save(self, *args, **kwargs):
        try:
            site = Site.objects.get(id=1)
            site.name = self.site_name
            site.domain = self.site_domain
            site.save()
        except:
            print "shit"
            pass

        super(Settings, self).save(*args, **kwargs)

class SettingsBlog(models.Model):
    blog_url = models.CharField(max_length=100,
            help_text='Should be something like blog/ or foo/blog/',
            default='blog/', null=True, blank=True)
    blog_title = models.CharField(max_length=100, blank=True, null=True)
    blog_description = models.TextField(blank=True, null=True)
    blog_posts = models.IntegerField('Index Post',default=5)


class ContactSettings(models.Model):
    url = models.CharField(max_length=100, default='/')
    succes_url = models.CharField(max_length=100)
    email = models.EmailField(default='to@example.com')

skylark/forms.py
from django import forms
from brasil.models import Post
from skylark.models import Settings
from skylark.models import SettingsBlog
from skylark.models import ContactSettings
from taggit.forms import TagField
# from django import newsforms
# from django.newsforms.widgets import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post



class SettingsForm(forms.ModelForm):

    class Meta:
        model = Settings


class SettingsBlogForm(forms.ModelForm):

    class Meta:
        model = SettingsBlog


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    topic = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

class SettingsContactForm(forms.ModelForm):

    class Meta:
        model = ContactSettings

brasil/views.py
# Create your views here.
from brasil.models import Post
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.core.exceptions import ObjectDoesNotExist
from skylark.models import SettingsBlog
from django.utils import simplejson as json

try:
    site_settings = SettingsBlog.objects.get(id=1)
    titulo = site_settings.blog_title
except:
    titulo = 'Pulp Fiction Bitches!'
    pass


def blog_index(request):
    posts = Post.objects.filter(published=True).order_by('-id')
    try:
        paginator = Paginator(posts, site_settings.blog_posts)
    except:
        paginator = Paginator(posts, 5)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        posts_pages = paginator.page(page)

    except (EmptyPage, InvalidPage):
        posts_pages = paginator.page(paginator.num_pages)

    context = {
            'posts': posts_pages,
            'titulo': titulo,
            }
    return render_to_response('blog_base.html',
            RequestContext(request, context))


def blog_detail(request, slug):
    detail_post = Post.objects.get(slug=slug)
    return render_to_response('blog_detail.html', {'post': detail_post},
            context_instance=RequestContext(request))

def blog_toggle(request, id):
    detail_post = Post.objects.get(id=id)
    if detail_post.published:
        detail_post.published = False
        detail_post.save()
    else:
        detail_post.published = True
        detail_post.save()

    return HttpResponseRedirect('/skylark/brasil/list/')

def save_inlinedit(request):
    try:
        content_body = json.loads(request.POST['raptor-content'])
        for content in content_body:
            content_current = Post.objects.get(id=content)
            content_current.body = content_body.get(content)
            content_current.save()
            return HttpResponse('saved')
    except:
        response = JSONResponse(request.POST['raptor-content'], {}, response_mimetype(request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        print json.dumps(request.POST['raptor-content'])
        return response

skylark/templates/brasil/blog.html
{% extends "base.html"   %}
{% block files %}
{% load media  %}
{% include_media 'redactor.js'  %}
{% include_media 'redactor.css'  %}
{% endblock  %}
{% block content  %}
<div class="ten columns">
  <div class="row">
    <fieldset>
      <legend> Add post </legend>
      <form method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="row collapse">
            {% if form.title.errors  %}
            {% for error in form.title.errors%}
            <div class="alert-box alert">
              Title: {{ error }}
            </div>
            {% endfor  %}
            {% endif  %}
            <div class="two mobile-one columns">
              <span class="prefix">Tittle</span>
            </div>
            <div class="ten mobile-three columns">
              <!--<input type="text" />-->
              {{form.title}}
            </div>
          </div>
        </div>
        <br />
        <div class="row">
          <div class="nine columns centered">
            <div class="six columns">
              {% if form.published.errors  %}
              {% for error in form.published.errors%}
              <span class="alert label">
                {{ error }}
              </span>
              {% endfor  %}
              {% endif  %}
              <div class="row">
                <div class="row collapse">
                  <div class="five columns">
                    Publish:
                  </div>
                  <div class="two columns end">
                    <span class="prefix">
                      {{form.published}}
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="six columns centered">
              {% if form.autor.errors  %}
              {% for error in form.autor.errors%}
              <div class="alert label">
                {{ error }}
              </div>
              {% endfor  %}
              <br/>
              <br/>
              {% endif  %}
              <div class="row">
                <div class="row collapse">
                  <div class="five columns">
                    Comments:
                  </div>
                  <div class="two columns end">
                    <span class="prefix">
                      {{form.enable_comments}}
                    </span>
                  </div>
                  <!--<input type="text" />-->
                  <br />
                  <br />
                </div>
              </div>
            </div>
          </div>
        </div>
        <br />
        <br />
        <div class="row">
          {% if form.body.errors  %}
          {% for error in form.body.errors%}
          <div class="alert-box alert">
            {{ error }}
          </div>
          {% endfor  %}
          {% endif  %}
          {{form.body}}
        </div>
        <br />
        <div class="row">
          {% if form.tags.errors  %}
          {% for error in form.tags.errors%}
          <div class="alert-box alert">
            {{ error }}
          </div>
          {% endfor  %}
          {% endif  %}
          <div class="row collapse">
            <div class="two mobile-one columns">
              <span class="prefix">Tags</span>
            </div>
            <div class="ten mobile-three columns">
              {{form.tags}}
            </div>
          </div>
        </div>
        <div class="two columns offset-by-ten">
          <input type="submit" value="Save" class="button success" />
          <br/>
          <br/>
        </div>
      </form>
    </fieldset>
  </div>
</div>
{% include "brasil/sidebar.html"  %}
{% endblock  %}
{% block scripts %}
<script type="text/javascript">
  $(document).foundationTopBar();
  $(document).foundationAlerts();
  $('textarea').autosize();
</script>
{% comment %}
<script type="text/javascript">
  $(document).ready(function(){
      $('#id_body').redactor({ wym: true });
      });
$('form').submit(function(){
    var editor = $('#id_body').getEditor().html();
    $('#id_body').val(editor);
    })
</script>
{% endcomment %}
{% include "redactorbody.html" %}
{% endblock %}

skylark/templates/brasil/blog_edit.html
{% extends "base.html"  %}
{% block  content %}
<div class="ten columns">
  <div class="row">
    <fieldset>
      <legend> Edit posts </legend>
      <div class="row">
        <div class="one columns">
          <input type="checkbox" class="left" ></input>
        </div>
        <div class="three columns">
          <select id="actions" class="custom dropdown left">
            <option>Delete</option>
            <option>Publish</option>
            <option>Draft</option>
          </select>
        </div>
        <div class="four columns ">
          <input placeholder="search" type="text" />
        </div>
      </div>
      <div class="row">
        <div class="row">
          {% for post in post %}
          <div class="twelve columns centered">
            <div class="one columns">
              <input type="checkbox" value="{{post.id}}" />
            </div>
            <a href="/brasil/{{post.id}}/">
              <div class="two columns">{{post.title}}</div></a>
            <div class="two columns">{{post.autor}}</div>
            <div class="two columns">{{post.creation_date}}</div>
            <div class="two columns">
              <a href="/brasil/delete/{{post.id}}/">
                Delete
              </a>
            </div>
            <div class="two columns">
              <a href="/brasil/toggle/{{post.id}}/">
                {% if post.published %}
                Draft
                {% else  %}
                Publish
                {% endif %}
              </a>
            </div>
          </div>
          {% endfor  %}
        </div>
      </div>
    </fieldset>
  </div>
</div>
{% include "brasil/sidebar.html"  %}
{% endblock  %}
{% block scripts %}
<script type="text/javascript">
  $(document).foundationTopBar();
  $(document).foundationAlerts();
  $('textarea').autosize();
  </script>
  <script type="text/javascript">
    $(document).ready(function(){
        $('#content').redactor({ wym: true });
        });
</script>
{% endblock %}

skylark/templates/brasil/blog_tags.html
{% extends "base.html"  %}
{% block  content %}
<div class="ten columns">
  <div class="row">
    <fieldset>
      <legend> Blog tags </legend>
      <div class="row">
        <div class="one columns">
          <input type="checkbox" class="left" ></input>
        </div>
        <div class="four columns ">
          <input placeholder="search" type="text" />
        </div>
      </div>
      <div class="row">
        <div class="row">
          {% for tag in tags %}
          <div class="twelve columns centered">
            <div class="one columns">
              <input type="checkbox" value="{{tag.id}}" />
            </div>
            <a href="/brasil/{{post.id}}/">
              <div class="two columns">{{tag.title}}</div>
            </a>
            <div class="two columns">
              <a href="/brasil/delete/{{tag.id}}/">
                Delete
              </a>
            </div>
          </div>
          {% endfor  %}
        </div>
      </div>
    </fieldset>
  </div>
</div>
{% include "brasil/sidebar.html"  %}
{% endblock  %}
{% block scripts %}
<script type="text/javascript">
  $(document).foundationTopBar();
  $(document).foundationAlerts();
  $('textarea').autosize();
  </script>
  <script type="text/javascript">
    $(document).ready(function(){
        $('#content').redactor({ wym: true });
        });
</script>
{% endblock %}

skylark/templates/brasil/post_list.html
{% extends "base.html"  %}
{% block  content %}
<div class="ten columns">
  <div class="row">
    <fieldset>
      <legend> Edit posts </legend>
      <div class="row">
        {%if posts%}
        <div class="ten columns centered">
          <table>
            {% for post in posts %}
            <tr>
              <td>
                <a href="/skylark/brasil/{{post.id}}/">
                  <div class="three columns">{{post.title}}</div></a>
              </td>
              <td>
                <div class="two columns">{{post.autor}}</div>
              </td>
              <td>
                <div class="two columns">
                  {{post.creation_date|date:"SHORT_DATE_FORMAT"}}
                </div>
              </td>
              <td>
                <div class="two columns">
                  <a href="/skylark/brasil/delete/{{post.id}}/">
                    Delete
                  </a>
                </div>
              </td>
              <td>
                <div class="two columns">
                  <a href="/skylark/brasil/toggle/{{post.id}}/">
                    {% if post.published %}
                    Draft
                    {% else  %}
                    Publish
                    {% endif %}
                  </a>
                </div>
              </td>
            </tr>
            {% endfor  %}
          </table>
        </div>
        {% else  %}
        <div class="five columns centered">
          <h1> No post in brasil </h1>
        </div>
        <a href="/skylark/brasil/">
          <span class="button secondary"> <-- Back to add one  </label>
        </a>
        {% endif %}
      </div>
    </fieldset>
  </div>
</div>
{% include "brasil/sidebar.html"  %}
{% endblock  %}
{% block scripts %}
<script type="text/javascript">
  $(document).foundationTopBar();
  $(document).foundationAlerts();
  $('textarea').autosize();
  </script>
  <script type="text/javascript">
    $(document).ready(function(){
        $('#content').redactor({ wym: true });
        });
</script>
{% endblock %}

skylark/templates/brasil/sidebar.html
{% load media %}
<div class="two columns float  right">
  <style type="text/css">
    .second-item{
      position: fixed;
    }
  </style>
  <div class="second-item">
    <a href="{% if post %}{% url brasil_detail post.slug %}
      {% else %}{% url brasil_index  %}{% endif %} ">
      <img src="{% media_url 'img/blog/seeitoninternet.png'%}" alt="" />
          <hr/>
          <center>
            <p>
            Preview
            </p>
          </center>
        </a>
        <a href="/skylark/brasil/list/">
          <img src="{% media_url 'img/blog/edit_post.png'%}" alt="" />
          <hr />
          <center>
            <p>
              Edit Posts
            </p>
          </a>
    </center>
    <a href="/skylark/brasil/tags/">
      <img src="{% media_url 'img/blog/tags.png' %}" alt="" />
      <hr />
      <center>
        <p>
          Sort by tags
        </p>
      </center>
    </a>
  </div>
</div>

skylark/templates/brasil/tags_list.html
{% extends "base.html"  %}
{% block  content %}
<div class="ten columns">
  <div class="row">
    <fieldset>
      <legend> Tags </legend>
      <div class="row">
        <ul class="block-grid five-up">
          {% for tag in tags %}
          <li>
              <div class="twelve columns centered">
                <a href="/skylark/brasil/tags/{{tag.slug}}/">
                  <div class="three columns">{{tag.name}}</div></a>
              </div>
          </li>
          {% endfor  %}
        </ul>
      </div>
    </fieldset>
  </div>
</div>
{% include "brasil/sidebar.html"  %}
{% endblock  %}
{% block scripts %}
<script type="text/javascript">
  $(document).foundationTopBar();
  $(document).foundationAlerts();
  $('textarea').autosize();
  </script>
  <script type="text/javascript">
    $(document).ready(function(){
        $('#content').redactor({ wym: true });
        });
</script>
{% endblock %}